# Form implementation generated from reading ui file 'app/ui/ui/find_note_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FindWindow(object):
    def setupUi(self, FindWindow):
        FindWindow.setObjectName("FindWindow")
        FindWindow.resize(706, 195)
        self.centralwidget = QtWidgets.QWidget(parent=FindWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.b_findnote = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_findnote.sizePolicy().hasHeightForWidth())
        self.b_findnote.setSizePolicy(sizePolicy)
        self.b_findnote.setObjectName("b_findnote")
        self.gridLayout.addWidget(self.b_findnote, 2, 0, 1, 1)
        self.texts = QtWidgets.QVBoxLayout()
        self.texts.setObjectName("texts")
        self.themefilter = QtWidgets.QHBoxLayout()
        self.themefilter.setObjectName("themefilter")
        self.chb_themefilter = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chb_themefilter.setObjectName("chb_themefilter")
        self.themefilter.addWidget(self.chb_themefilter)
        self.t_themefilter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.t_themefilter.setObjectName("t_themefilter")
        self.themefilter.addWidget(self.t_themefilter)
        self.texts.addLayout(self.themefilter)
        self.contentfilter = QtWidgets.QHBoxLayout()
        self.contentfilter.setObjectName("contentfilter")
        self.chb_contentfilter = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chb_contentfilter.setEnabled(True)
        self.chb_contentfilter.setChecked(False)
        self.chb_contentfilter.setObjectName("chb_contentfilter")
        self.contentfilter.addWidget(self.chb_contentfilter)
        self.t_contentfilter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.t_contentfilter.setObjectName("t_contentfilter")
        self.contentfilter.addWidget(self.t_contentfilter)
        self.texts.addLayout(self.contentfilter)
        self.datefilter = QtWidgets.QHBoxLayout()
        self.datefilter.setObjectName("datefilter")
        self.chb_datefilter = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chb_datefilter.setObjectName("chb_datefilter")
        self.datefilter.addWidget(self.chb_datefilter)
        self.t_datefilter = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.t_datefilter.setCalendarPopup(True)
        self.t_datefilter.setObjectName("t_datefilter")
        self.datefilter.addWidget(self.t_datefilter)
        self.texts.addLayout(self.datefilter)
        self.gridLayout.addLayout(self.texts, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        FindWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FindWindow)
        QtCore.QMetaObject.connectSlotsByName(FindWindow)

    def retranslateUi(self, FindWindow):
        _translate = QtCore.QCoreApplication.translate
        FindWindow.setWindowTitle(_translate("FindWindow", "Найти заметки"))
        self.b_findnote.setText(_translate("FindWindow", "Найти"))
        self.chb_themefilter.setText(_translate("FindWindow", "Фильтр по теме"))
        self.chb_contentfilter.setText(_translate("FindWindow", "Фильтр по содержимому"))
        self.chb_datefilter.setText(_translate("FindWindow", "Фильтр по дате"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindWindow = QtWidgets.QMainWindow()
    ui = Ui_FindWindow()
    ui.setupUi(FindWindow)
    FindWindow.show()
    sys.exit(app.exec())
